---
- name: Check for live devices for report
  hosts: ios
  gather_facts: false
  roles:
    - role: hostalive
      tags: ['hostalive']
- name: Gather facts and create report on alive host group
  hosts: running_hosts
  gather_facts: false
  roles:
    - role: networkverreport
      tags: ['netreport']

    - role: slackalerts
      tags: ['slackalert']
