---
# Playbook to test new roles and tags
- name: Generate Network Reports in container
  hosts: ios
  gather_facts: false
  roles:
    - role: reportcontainer
      tags: ['creatcontainer']
    - role: networkverreport
      tags: ['netreport']
    - role: slackalerts
      tags: ['slackalert']
