---

- name: Generate Network Reports in container
  hosts: ios
  gather_facts: false
  roles:
    - role: networkverreport
      tags: ['netreport']
      
    - role: slackalerts
      tags: ['slackalert']
