---
- name: Check for live devices for report
  hosts: ios
  gather_facts: false
  tasks:
  - block:
      - name: determine hosts that are up
        wait_for_connection:
          timeout: 5
        vars:
          ansible_connection: network_cli
          ansible_network_os: ios
      - name: add devices with connectivity to the "running_hosts" group
        group_by:
          key: "running_hosts"
    rescue:
      - debug: msg="Cannot connect to {{inventory_hostname}}"
- name: Gather facts and create report
  hosts: running_hosts
  gather_facts: false
  roles:
    - role: networkverreport
      tags: ['netreport']

    - role: slackalerts
      tags: ['slackalert']
