---
# Playbook to test new roles and tags
- name: Install and configure Container for Reports
  hosts: all
  gather_facts: true
  roles:
    - role: reportcontainer
      tags: ['creatcontainer']
    - role: osreport
      tags: ['osreport']
    - role: slackalerts
      tags: ['slackalert']
