---
# Playbook to test new roles and tags
- name: Install and configure Container for Reports
  hosts: all
  gather_facts: false
  ignore_unreachable: true
  roles:
    - role: osreport
      tags: ['osreport']

    - role: slackalerts
      tags: ['slackalert']
