---
# Playbook to test new roles and tags
- name: Check for live devices for report
  hosts: all
  gather_facts: false
  tasks:
  - block:
      - name: determine hosts that are up
        wait_for_connection:
          timeout: 5
        vars:
          ansible_connection: ssh
      - name: add devices with connectivity to the "running_hosts" group
        group_by:
          key: "running_hosts"
    rescue:
      - debug: msg="Cannot connect to {{inventory_hostname}}"
- name: Gather facts and create report
  hosts: running_hosts
  gather_facts: false
  roles:
    - role: osreport
      tags: ['osreport']

    - role: slackalerts
      tags: ['slackalert']
