---
    - include: preflight-checks-os-report.yml



    - name: gathering all IOS facts
      ios_facts:
      register: all_facts

    - name: HTML report is created
      vars:

        ansbile_password: "{{ reporthost_password }}"
      template:
        src: templates/report-ios.j2
        dest: "{{ home_dir }}/reports/ios.html"
      remote_user: "{{ reporthost_user }}"
      run_once: True
      delegate_to: "{{ container_host }}"
