---
    - include: preflight-checks-os-report.yml



    - name: gathering all IOS facts
      ios_facts:
      register: all_facts

    - name: Create the OS report and limit it to the container host
      block:
      - name: OS Report directory is present
        file:
          path: "{{ home_dir }}/ios-report/css"
          state: directory

      - name: CSS is present on remote host
        copy:
          src: CSS/main.css
          dest: "{{ home_dir }}/ios-report/css/main.css"

      - name: HTML report is created
        template:
          src: templates/report-ios.j2
          dest: "{{ home_dir }}/ios-report/iosreport.html"

      - name: OS Report container is launched
        containers.podman.podman_container:
          name: os-report
          image: quay.io/samander/convert2rhel-os-dashboard:latest
          state: started
          volume:
            - "{{ home_dir }}/ios-report:/var/report:Z"
          ports:
            - "{{ target_port }}:8080"
      run_once: True
      delegate_to: "{{ container_host }}"
