---
    - include: preflight-checks-os-report.yml

    - name: Create the OS report and limit it to the container host
      block:

      - name: HTML report is created
        remote_user: "{{ report_user }}"
        template:
          src: templates/report-osversion.j2
          dest: "{{ home_dir }}/reports/os.html"
      run_once: True
      delegate_to: "{{ container_host }}"
