---
    - include: preflight-checks-os-report.yml

    - name: Gather facts on inventory
      setup:
      register: all_facts
      ignore_unreachable: false
    - name: Show all facts
      debug:
          var: all_facts
          verbosity: 2

    - name: HTML report is created
      remote_user: "{{ report_user }}"
      template:
        src: templates/report-osversion.j2
        dest: "{{ home_dir }}/reports/os.html"

      run_once: True
      delegate_to: "{{ container_host }}"
