---
    - include: preflight-checks-os-report.yml

    - name: Gather facts on inventory
      setup:
      ignore_unreachable: true
      register: all_facts

    - name: HTML report is created
      remote_user: "{{ report_user }}"
      template:
        src: templates/report-osversion.j2
        dest: "{{ home_dir }}/reports/os.html"
      run_once: True
      delegate_to: "{{ container_host }}"
