---
    - include: preflight-checks-os-report.yml

    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to {{inventory_hostname}}"


    - name: Gather facts on host that are up
      hosts: running_hosts
      tasks:
        - name: Gather facts on inventory
          setup:
          register: all_facts

        - name: HTML report is created
          remote_user: "{{ report_user }}"
          template:
            src: templates/report-osversion.j2
            dest: "{{ home_dir }}/reports/os.html"

          run_once: True
          delegate_to: "{{ container_host }}"
