---
- include: preflight-checks.yml
- name: Restart Container
  containers.podman.podman_container:
    name: report
    state: started
    force_restart: yes
  run_once: True
  delegate_to: "{{ container_host }}"
