---
- include: preflight-checks.yml
- name: Restart Container
  remote_user: "{{ report_user }}"
  containers.podman.podman_container:
    name: report
    image: quay.io/samander/nginx-report-base:latest
    state: started
    restart: yes
    volume:
      - "{{ home_dir }}/reports:/var/report:Z"
    ports:
      - "{{ target_port }}:8080"
  run_once: True
  delegate_to: "{{ container_host }}"
